//---------//
// IMPORTS //
//---------//

local bundle = import 'lib/bundle.libsonnet';
local file_paths = import 'lib/file_paths.libsonnet';
local k = import 'lib/karabiner.libsonnet';

local unless_hypervisor_ide_remoteDesktop_terminalEmulator = k.condition(
  'unless',
  bundle.hypervisors + bundle.ides + bundle.remoteDesktops + bundle.terminalEmulators,
);

local unless_hypervisor_ide_remoteDesktop = k.condition(
  'unless',
  bundle.hypervisors + bundle.ides + bundle.remoteDesktops,
);

local unless_remoteDesktop_hypervisor = k.condition(
  'unless',
  bundle.hypervisors + bundle.remoteDesktops,
);

//------//
// MAIN //
//------//

{
  profiles: [
    {
      complex_modifications: {
        title: 'Windows Shortcuts',
        rules: [
          k.rule('Insert (Ctrl)',
                 k.input('insert', ['control']),
                 k.outputKey('c', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('Insert (Shift)',
                 k.input('insert', ['shift']),
                 k.outputKey('v', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('Home (Ctrl+Shift)',
                 k.input('home', ['control', 'shift']),
                 k.outputKey('up_arrow', ['command', 'shift']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('Home (Shift)',
                 k.input('home', ['shift']),
                 k.outputKey('left_arrow', ['command', 'shift']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('Home (Ctrl)',
                 k.input('home', ['control']),
                 k.outputKey('up_arrow', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('Home',
                 k.input('home'),
                 k.outputKey('left_arrow', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('End (Ctrl+Shift)',
                 k.input('end', ['control', 'shift']),
                 k.outputKey('down_arrow', ['command', 'shift']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('End (Shift)',
                 k.input('end', ['shift']),
                 k.outputKey('right_arrow', ['command', 'shift']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('End (Ctrl)',
                 k.input('end', ['control']),
                 k.outputKey('down_arrow', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('End',
                 k.input('end'),
                 k.outputKey('right_arrow', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('Left Arrow (Ctrl)',
                 k.input('left_arrow', ['control']),
                 k.outputKey('left_arrow', ['option']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('Left Arrow (Ctrl+Shift)',
                 k.input('left_arrow', ['control', 'shift']),
                 k.outputKey('left_arrow', ['option', 'shift']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('Right Arrow (Ctrl)',
                 k.input('right_arrow', ['control']),
                 k.outputKey('right_arrow', ['option']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('Right Arrow (Ctrl+Shift)',
                 k.input('right_arrow', ['control', 'shift']),
                 k.outputKey('right_arrow', ['option', 'shift']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('Backspace (Ctrl)',
                 k.input('delete_or_backspace', ['control']),
                 k.outputKey('delete_or_backspace', ['option']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('Delete (Ctrl)',
                 k.input('delete_forward', ['control']),
                 k.outputKey('delete_forward', ['option']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('Enter (Ctrl)',
                 k.input('return_or_enter', ['control']),
                 k.outputKey('return_or_enter', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('Enter (Ctrl+Shift)',
                 k.input('return_or_enter', ['control', 'shift']),
                 k.outputKey('return_or_enter', ['command', 'shift']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('A (Ctrl)',
                 k.input('a', ['control']),
                 k.outputKey('a', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('B (Ctrl)',
                 k.input('b', ['control']),
                 k.outputKey('b', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('C (Ctrl)',
                 k.input('c', ['left_control']),
                 k.outputKey('c', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('F (Ctrl)',
                 k.input('f', ['control']),
                 k.outputKey('f', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('I (Ctrl)',
                 k.input('i', ['control']),
                 k.outputKey('i', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('N (Ctrl)',
                 k.input('n', ['control']),
                 k.outputKey('n', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('O (Ctrl)',
                 k.input('o', ['control']),
                 k.outputKey('o', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('P (Ctrl)',
                 k.input('p', ['control']),
                 k.outputKey('p', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('R (Ctrl)',
                 k.input('r', ['control']),
                 k.outputKey('r', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('S (Ctrl)',
                 k.input('s', ['control']),
                 k.outputKey('s', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('T (Ctrl)',
                 k.input('t', ['control']),
                 k.outputKey('t', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('U (Ctrl)',
                 k.input('u', ['control']),
                 k.outputKey('u', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('V (Ctrl)',
                 k.input('v', ['control']),
                 k.outputKey('v', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('W (Ctrl)',
                 k.input('w', ['control']),
                 k.outputKey('w', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('X (Ctrl)',
                 k.input('x', ['control']),
                 k.outputKey('x', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('Y (Ctrl)',
                 k.input('y', ['control']),
                 k.outputKey('y', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('Z (Ctrl)',
                 k.input('z', ['control']),
                 k.outputKey('z', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('Space (Ctrl)',
                 k.input('spacebar', ['control']),
                 k.outputKey('spacebar', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('F1',
                 k.input('f1'),
                 k.outputKey('slash', ['command', 'shift']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          k.rule('F3',
                 k.input('f3'),
                 k.outputKey('g', ['command']),
                 unless_hypervisor_ide_remoteDesktop_terminalEmulator),
          ////////////////////////////////////////////////////////////////////////////////////////////////
          k.rule('L (Win) [Lock Screen] [Always]',
                 k.input('l', ['command']),
                 k.outputKey('q', ['control', 'command'])),
          k.rule('L (Win) [Sleep] [Always]',
                 k.input('l', ['command']),
                 k.outputKey('power', ['control', 'shift'])),
          k.rule('L (Alt+Ctrl) [Lock Screen] [Always]',
                 k.input('l', ['control', 'option']),
                 k.outputKey('q', ['control', 'command'])),
          k.rule('L (Alt+Ctrl) [Sleep] [Always]',
                 k.input('l', ['control', 'option']),
                 k.outputKey('power', ['control', 'shift'])),
          ////////////////////////////////////////////////////////////////////////////////////////////////
          k.rule('Insert (Ctrl) [+Terminal Emulators]',
                 k.input('insert', ['control']),
                 k.outputKey('c', ['command']),
                 unless_hypervisor_ide_remoteDesktop),
          k.rule('Insert (Shift) [+Terminal Emulators]',
                 k.input('insert', ['shift']),
                 k.outputKey('v', ['command']),
                 unless_hypervisor_ide_remoteDesktop),
          k.rule('/ (Ctrl) [+Terminal Emulators]',
                 k.input('slash', ['control']),
                 k.outputKey('slash', ['command']),
                 unless_hypervisor_ide_remoteDesktop),
          k.rule('F4 (Alt) [+Terminal Emulators]',
                 k.input('f4', ['option']),
                 k.outputKey('q', ['command']),
                 unless_hypervisor_ide_remoteDesktop),
          ////////////////////////////////////////////////////////////////////////////////////////////////
          k.rule('C (Ctrl+Shift) [Only Terminal Emulators]',
                 k.input('c', ['control', 'shift']),
                 k.outputKey('c', ['command']),
                 k.condition('if', bundle.terminalEmulators)),
          k.rule('V (Ctrl+Shift) [Only Terminal Emulators]',
                 k.input('v', ['control', 'shift']),
                 k.outputKey('v', ['command']),
                 k.condition('if', bundle.terminalEmulators)),
          ////////////////////////////////////////////////////////////////////////////////////////////////
          k.rule('H (Ctrl) [Only Web Browsers]',
                 k.input('h', ['control']),
                 k.outputKey('y', ['command']),
                 k.condition('if', bundle.webBrowsers)),
          k.rule('L (Ctrl) [Only Web Browsers]',
                 k.input('l', ['control']),
                 k.outputKey('l', ['command']),
                 k.condition('if', bundle.webBrowsers)),
          ////////////////////////////////////////////////////////////////////////////////////////////////
          k.rule('PrtSc [Print Screen] [Always]',
                 k.input('print_screen'),
                 k.outputKey('4', ['left_command', 'left_shift'])),
          k.rule('PrtSc (Shift) [Print Screen to clipboard] [Always]',
                 k.input('print_screen', ['shift']),
                 k.outputKey('4', ['left_control', 'left_command', 'left_shift'])),
          k.rule('PrtSc (Ctrl) [Print Screen to clipboard] [Always]',
                 k.input('print_screen', ['control']),
                 k.outputKey('5', ['left_command', 'left_shift'])),
        ],
      },
      devices: [
        {
          identifiers: { is_keyboard: true },
          ignore: true,
        },
      ],
      name: 'Default profile',
      selected: true,
      virtual_hid_keyboard: { keyboard_type_v2: 'ansi' },
    },
  ],
}
